-- phpMyAdmin SQL Dump
-- version 3.4.10.1deb1
-- http://www.phpmyadmin.net
--
-- Host: 10.101.1.80
-- Generation Time: Jan 17, 2014 at 11:02 PM
-- Server version: 5.5.30
-- PHP Version: 5.3.10-1ubuntu3.4

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `moviefinder`
--

-- --------------------------------------------------------

--
-- Table structure for table `data`
--

CREATE TABLE IF NOT EXISTS `data` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(250) NOT NULL,
  `summary` varchar(500) NOT NULL,
  `genre` varchar(250) NOT NULL,
  `rating` varchar(3) NOT NULL,
  `length` varchar(255) NOT NULL,
  `backgroundimgurl` varchar(500) NOT NULL,
  `posterimg` varchar(255) NOT NULL,
  `releaseYear` varchar(4) NOT NULL,
  `youtubeID` varchar(255) NOT NULL,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `storyline` varchar(500) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=48 ;

--
-- Dumping data for table `data`
--

INSERT INTO `data` (`id`, `title`, `summary`, `genre`, `rating`, `length`, `backgroundimgurl`, `posterimg`, `releaseYear`, `youtubeID`, `date`, `storyline`) VALUES
(11, 'Enter the Void', 'An American drug dealer living in Tokyo is betrayed by his best friend and killed in a drug deal gone bad. His soul, observing the repercussions of his death, seeks resurrection.', 'Drama', '7.1', '03:08:00', 'images/backgroundimg/enter-the-void-18-31770.jpg', 'images/backgroundimg/600full-enter-the-void-poster.jpg', '2009', 'bKRxDP--e-Y', '2014-01-07 14:20:56', 'Tokyo''s nasty underside, seen primarily through the eyes of Oscar, a heavy drug user, whose sister Linda is a stripper. Oscar also has flashbacks to his childhood when trauma upends the siblings. Oscar''s drug-fed hallucinations alter Tokyo''s already-disconcerting nights, and after the police shoot him, he can float above and look down: on his sister''s sorrow, on the rooms of a love hotel, and on life at even a molecular level. The spectrum''s colors can be beautiful; it''s people''s colorless lives'),
(12, 'Generation Iron', 'A documentary that follows top bodybuilders as they train to compete in the Mr. Olympia competition.', 'Documentary', '6.9', '01:06:00', 'images/backgroundimg/generationiron.jpg', 'images/backgroundimg/Generation%20Iron%20Final%20PosterHiRez.jpg', '2013', '1O6wMhDRST0', '2014-01-07 21:17:10', 'From the producer of the original classic Pumping Iron'', comes &quot;Generation Iron&quot; the long awaited true story of dedication, rivalry, victory, defeat, redemption and triumph... The film examines the professional sport of bodybuilding today and gives us access to the lives of current bodybuilding stars Phil Heath, Kai Greene, Branch Warren, Dennis Wolf, Victor Martinez, Hidetada Yamagishi as well as ambitious newcomer Ben Pakulski and European sensation Roelly Winklaar on their journey t'),
(13, 'The Hobbit - An Unexpected Journey', 'A younger and more reluctant Hobbit, Bilbo Baggins, sets out on an &quot;unexpected journey&quot; to the Lonely Mountain with a spirited group of Dwarves to reclaim their stolen mountain home from a dragon named Smaug.', 'Adventure', '8.0', '03:29:00', 'images/backgroundimg/the-hobbit-movie-48-fps-650x0.jpg', 'images/backgroundimg/hobbit-bilbo-sword-i13369.jpg', '2012', 'JTSoD4BBCJc', '2014-01-07 14:27:47', 'Bilbo Baggins is swept into a quest to reclaim the lost Dwarf Kingdom of Erebor from the fearsome dragon Smaug. Approached out of the blue by the wizard Gandalf the Grey, Bilbo finds himself joining a company of thirteen dwarves led by the legendary warrior, Thorin Oakenshield. Their journey will take them into the Wild; through treacherous lands swarming with Goblins and Orcs, deadly Wargs and Giant Spiders, Shapeshifters and Sorcerers. Although their goal lies to the East and the wastelands of'),
(14, 'Jobs', 'The story of Steve Jobs'' ascension from college dropout into one of the most revered creative entrepreneurs of the 20th century.', 'Drama', '5.7', '02:08:00', 'images/backgroundimg/steve-jobs-movie-jobs2013-poster-ashton-kutcher-jobs-movie-official-movie-poster-jobs-movie-pictures-jobs-2013-movie-stills1.jpg', 'images/backgroundimg/jobs-movie-poster-2013-1020755614.jpg', '2013', 'FrvkCS0ZGPU', '2014-01-07 14:28:54', 'The story of Steve Jobs'' ascension from college dropout into one of the most revered creative entrepreneurs of the 20th century.'),
(15, 'Fast &amp; Furious 6', 'Hobbs has Dom and Brian reassemble their crew in order to take down a mastermind who commands an organization of mercenary drivers across 12 countries. Payment? Full pardons for them all.', 'Action', '7.2', '02:10:00', 'images/backgroundimg/fastandfurious6.jpg', 'images/backgroundimg/fastfurious6.jpg', '2013', 'dKi5XoeTN0k', '2014-01-07 21:54:56', 'Since Dom (Diesel) and Brian''s (Walker) Rio heist toppled a kingpin''s empire and left their crew with $100 million, our heroes have scattered across the globe. But their inability to return home and living forever on the lam have left their lives incomplete. Meanwhile, Hobbs (Johnson) has been tracking an organization of lethally skilled mercenary drivers across 12 countries, whose mastermind (Evans) is aided by a ruthless second-in-command revealed to be the love Dom thought was dead, Letty (Ro'),
(17, 'The Lord of the Rings: The Two Towers', 'While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron''s new ally, Saruman, and his hordes of Isengard.', 'Adventure', '8.7', '02:59:00', 'images/backgroundimg/the-lord-of-the-rings-the-two-towers13.jpg', 'images/backgroundimg/two-towers-poster.jpg', '2002', 'zcGti6pfsMw', '2014-01-08 15:44:38', 'Sauron''s forces increase. His allies grow. The Ringwraiths return in an even more frightening form. Saruman''s army of Uruk Hai is ready to launch an assault against Aragorn and the people of Rohan. Yet, the Fellowship is broken and Boromir is dead. For the little hope that is left, Frodo and Sam march on into Mordor, unprotected. A number of new allies join with Aragorn, Gimli, Legolas, Pippin and Merry. And they must defend Rohan and attack Isengard. Yet, while all this is going on, Sauron''s tr'),
(18, 'The Lord of the Rings: The Return of the King', 'Gandalf and Aragorn lead the World of Men against Sauron''s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.', 'Adventure', '8.9', '03:21:00', 'images/backgroundimg/the-lord-of-the-rings-the-return-of-the-king-4.jpg', 'images/backgroundimg/lord_of_the_rings_the_return_of_the_king_xlg.jpg', '2003', 'r5X-hFf6Bwo', '2014-01-08 15:50:07', 'While Frodo &amp; Sam continue to approach Mount Doom to destroy the One Ring, unaware of the path Gollum is leading them, the former Fellowship aid Rohan &amp; Gondor in a great battle in the Pelennor Fields, Minas Tirith and the Black Gates as Sauron wages his last war against Middle-Earth.'),
(19, 'The Matrix', 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.', 'Sci-fi', '8.7', '02:16:00', 'images/backgroundimg/the-matrix-poster.jpg', 'images/backgroundimg/the_matrix_1999_poster.jpg', '1999', 'm8e-FF8MsqU', '2014-01-07 14:19:57', 'Thomas A. Anderson is a man living two lives. By day he is an average computer programmer and by night a hacker known as Neo. Neo has always questioned his reality, but the truth is far beyond his imagination. Neo finds himself targeted by the police when he is contacted by Morpheus, a legendary computer hacker branded a terrorist by the government. Morpheus awakens Neo to the real world, a ravaged wasteland where most of humanity have been captured by a race of machines that live off of the hum'),
(24, 'Wall-E', 'In the distant future, a small waste collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.', 'Family', '8.5', '01:38:00', 'images/backgroundimg/Fantastic_Wall-E_and-Eve-Cartoon_Wallpaper.jpg', 'images/backgroundimg/walleposter.jpg', '2008', '8-_9n5DtKOc', '2014-01-08 14:44:51', 'In a distant, but not so unrealistic, future where mankind has abandoned earth because it has become covered with trash from products sold by the powerful multi-national Buy N Large corporation, WALL-E, a garbage collecting robot has been left to clean up the mess. Mesmerized with trinkets of Earth''s history and show tunes, WALL-E is alone on Earth except for a sprightly pet cockroach. One day, EVE, a sleek (and dangerous) reconnaissance robot, is sent to Earth to find proof that life is once ag'),
(20, 'Don Jon', 'A New Jersey guy dedicated to his family, friends, and church, develops unrealistic expectations from watching porn and works to find happiness and intimacy with his potential true love.', 'Romance', '6.9', '01:30:00', 'images/backgroundimg/don-jon-image04.jpg', 'images/backgroundimg/don-jon-poster.jpg', '2013', '6615kYTpOSU', '2014-01-07 14:17:56', 'Jon Martello objectifies everything in his life: his apartment, his car, his family, his church, and, of course, women. His buddies even call him Don Jon because of his ability to pull &quot;10s&quot; every weekend without fail. Yet even the finest flings don''t compare to the transcendent bliss he achieves alone in front of the computer watching pornography. Dissatisfied, he embarks on a journey to find a more gratifying sex life, but ends up learning larger lessons of life and love through rela'),
(21, 'Iron Man', 'When wealthy industrialist Tony Stark is forced to build an armored suit after a life-threatening incident, he ultimately decides to use its technology to fight against evil.', 'Action', '7.9', '02:06:00', 'images/backgroundimg/Iron_Man_2.jpg', 'images/backgroundimg/hi-res-domestic-poster-iron-man-879214_864_1280.jpg', '2008', '8hYlB38asDY', '2014-01-07 14:17:49', 'Tony Stark is the complete playboy who also happens to be an engineering genius. While in Afghanistan demonstrating a new missile, he''s captured and wounded. His captors want him to assemble a missile for them but instead he creates an armored suit and a means to prevent his death from the shrapnel left in his chest by the attack. He uses the armored suit to escape. Back in the U.S. he announces his company will cease making weapons and he begins work on an updated armored suit only to find that'),
(22, 'Batman Begins', 'After training with his mentor, Batman begins his war on crime to free the crime-ridden Gotham City from corruption that the Scarecrow and the League of Shadows have cast upon it.', 'Action', '8.3', '02:20:00', 'images/backgroundimg/batman_begins_2005_3421_wallpaper.jpg', 'images/backgroundimg/Batman_Begins_poster6.jpg', '2005', 'vak9ZLfhGnQ', '2014-01-07 21:52:02', 'When his parents were killed, millionaire playboy Bruce Wayne relocates to Asia when he is mentored by Henri Ducard and Ra''s Al Ghul in how to fight evil. When learning about the plan to wipe out evil in Gotham City by Ducard, Bruce prevents this plan from getting any further and heads back to his home. Back in his original surroundings, Bruce adopts the image of a bat to strike fear into the criminals and the corrupt as the icon known as ''Batman''. But it doesn''t stay quiet for long.'),
(23, 'Pulp Fiction', 'The lives of two mob hit men, a boxer, a gangster''s wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 'Crime', '9.0', '02:34:00', 'images/backgroundimg/pulp_fictionbg.jpg', 'images/backgroundimg/pulp_fiction.jpg', '1994', 's7EdQ4FqbhY', '2014-01-07 22:03:14', 'Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.'),
(25, 'Argo', 'Acting under the cover of a Hollywood producer scouting a location for a science fiction film, a CIA agent launches a dangerous operation to rescue six Americans in Tehran during the U.S. hostage crisis in Iran in 1980.', 'Drama', '7.8', '02:00:00', 'images/backgroundimg/wEGLbT32350.jpg', 'images/backgroundimg/Argo-Movie-Poster.jpg', '2012', 'w918Eh3fij0', '2014-01-08 15:29:33', 'In 1979, the American embassy in Iran was invaded by Iranian revolutionaries and several Americans were taken hostage. However, six managed to escape to the official residence of the Canadian Ambassador and the CIA was ordered to get them out of the country. With few options, exfiltration expert Tony Mendez devised a daring plan: create a phony Canadian film project looking to shoot in Iran and smuggle the Americans out as its production crew. With the help of some trusted Hollywood contacts, Me'),
(39, 'The Dark Knight Rises', 'Eight years on, a new evil rises from where the Batman and Commissioner Gordon tried to bury it, causing the Batman to resurface and fight to protect Gotham City... the very city which brands him an enemy.', 'Action', '8.6', '02:45:00', 'http://www.hdwallpapers.in/walls/batman_film_the_dark_knight_rises-wide.jpg', 'http://www.cinemablend.com/images/news/31034/New_Dark_Knight_Rises_Poster_Arrives_Online_1337636698.jpg', '2012', 'GokKUqLcvD8', '2014-01-08 15:56:45', 'Despite his tarnished reputation after the events of The Dark Knight, in which he took the rap for Dent''s crimes, Batman feels compelled to intervene to assist the city and its police force which is struggling to cope with Bane''s plans to destroy the city.'),
(27, 'The Shawshank Redemption', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 'Drama', '9.3', '02:22:00', 'images/backgroundimg/shawshank3.jpg', 'images/backgroundimg/the-shawshank-redemption-movie-poster-1994-1020191906.jpg', '1994', '6hB3S9bIaco', '2014-01-08 15:28:46', 'Andy Dufresne is a young and successful banker whose life changes drastically when he is convicted and sentenced to life imprisonment for the murder of his wife and her lover. Set in the 1940''s, the film shows how Andy, with the help of his friend Red, the prison entrepreneur, turns out to be a most unconventional prisoner.'),
(28, 'Paranormal Activity: The Marked Ones', 'Jessie begins experiencing a number of disturbing and unexplainable things after the death of his neighbor. As he investigates, it isn''t long before Jessie finds he''s been marked for possession by a malevolent demonic entity, and it''s only a matter of time before he is completely under its control...', 'Horror', '5.3', '01:24:00', 'http://www.entertainmentwallpaper.com/images/res1920x1080/movie/paranormal-activity-the-marked-ones03.jpg', 'http://cultfix.co.uk/wp-content/uploads/Paranormal-Activity-marked-ones-poster-300x444.jpg', '2014', 'J39iyK_aqDE', '2014-01-08 14:38:36', 'Jessie begins experiencing a number of disturbing and unexplainable things after the death of his neighbor. As he investigates, it isn''t long before Jessie finds he''s been marked for possession by a malevolent demonic entity, and it''s only a matter of time before he is completely under its control... '),
(29, 'Gravity', 'A medical engineer and an astronaut work together to survive after an accident leaves them adrift in space.', 'Thriller', '8.3', '01:31:00', 'images/backgroundimg/Wallpaper-HD-Gravity-.jpg', 'images/backgroundimg/Gravity-Poster-George-Clooney-600x887.jpg', '2013', 'OiTiKOy59o4', '2014-01-08 15:27:18', 'Dr. Ryan Stone (Sandra Bullock) is a brilliant medical engineer on her first shuttle mission, with veteran astronaut Matt Kowalsky (George Clooney) in command of his last flight before retiring. But on a seemingly routine spacewalk, disaster strikes. The shuttle is destroyed, leaving Stone and Kowalsky completely alone - tethered to nothing but each other and spiraling out into the blackness.'),
(30, 'The Curious Case of Benjamin Button', 'Tells the story of Benjamin Button, a man who starts aging backwards with bizarre consequences.', 'Drama', '7.8', '02:46:00', 'http://2.bp.blogspot.com/-hNZymtnIWZc/Tms13yzEMKI/AAAAAAAADc8/60errsaYbfY/s1600/The+Curious+Case+of+Benjamin+Button+01.jpg', 'http://www.smh.com.au/benjaminbutton/images/movie-poster-Benjamin-Button.jpg', '2008', 'rAYtpZgelAM', '2014-01-08 14:25:12', 'On the day that Hurricane Katrina hits New Orleans, elderly Daisy Williams (nee Fuller) is on her deathbed in a New Orleans hospital. At her side is her adult daughter, Caroline. Daisy asks Caroline to read to her aloud the diary of Daisy''s lifelong friend, Benjamin Button. Benjamin''s diary recounts his entire extraordinary life, the primary unusual aspect of which was his aging backwards, being diagnosed with several aging diseases at birth and thus given little chance of survival, but who does'),
(31, 'Drive', 'A mysterious Hollywood stuntman, mechanic and getaway driver lands himself in trouble when he helps out his neighbor.', 'Crime', '7.9', '01:40:00', 'images/backgroundimg/drive.jpg', 'images/backgroundimg/Nicolas%252BWinding%252BRefn%252BRyan%252BGosling%252Bdrive%252Bposter%252B002.jpg', '2011', 'CWX34ShfcsE', '2014-01-08 15:27:51', 'A mysterious man who has multiple jobs as a garage mechanic, a Hollywood stuntman and a getaway driver seems to be trying to escape his shady past as he falls for his neighbor - whose husband is in prison and who''s looking after her child alone. Meanwhile, his garage mechanic boss is trying to set up a race team using gangland money, which implicates our driver as he is to be used as the race team''s main driver. Our hero gets more than he bargained for when he meets the man who is married to the'),
(32, 'Mamma Mia', 'The story of a bride-to-be trying to find her real father told using hit songs by the popular ''70s group ABBA.', 'Musical', '6.3', '01:48:00', 'images/backgroundimg/mamma-mia41.jpg', 'images/backgroundimg/mamma-mia-poster-1.jpg', '2008', 'yzhxHsqQvsI', '2014-01-08 15:26:46', 'Set on a colorful Greek island, the plot serves as a background for a wealth of ABBA songs. A young woman about to be married discovers that any one of three men could be her father. She invites all three to the wedding without telling her mother, Donna, who was once the lead singer of Donna and the Dynamos. In the meantime, Donna has invited her backup singers, Rosie and Tanya.'),
(33, 'King Kong', 'In 1933 New York, an overly ambitious movie producer coerces his cast and hired ship crew to travel to mysterious Skull Island, where they encounter Kong, a giant ape who is immediately smitten with leading lady Ann Darrow.', 'Adventure', '7.3', '03:07:00', 'images/backgroundimg/84840.jpg', 'images/backgroundimg/king-kong-poster.jpg', '2005', 'AYaTCPbYGdk', '2014-01-08 15:26:18', 'Carl Denham needs to finish his movie and has the perfect location; Skull Island. But he still needs to find a leading lady. This ''soon-to-be-unfortunate'' soul is Ann Darrow. No one knows what they will encounter on this island and why it is so mysterious, but once they reach it, they will soon find out. Living on this hidden island is a giant gorilla and this beast now has Ann is its grasps. Carl and Ann''s new love, Jack Driscoll must travel through the jungle looking for Kong and Ann, whilst a'),
(34, 'Vanilla Sky', 'A successful publisher finds his life taking a turn for the surreal after a car accident with a jaded lover.', 'Romance', '6.9', '02:16:00', 'images/backgroundimg/Vanilla-Sky-pen-C3-A9lope-cruz-225739_1200_780.jpg', 'images/backgroundimg/vanilla-sky-movie-poster-2001-1020192775.jpg', '2001', 'k09OX40NLUw', '2014-01-08 15:59:34', 'Incarcerated and charged with murder, David Aames Jr. is telling the story of how he got to where he is to McCabe, the police psychologist. That story includes: being the 51% shareholder of a major publishing firm, which he inherited from his long deceased parents; the firm''s board, appointed by David Aames Sr., being the 49% shareholders who would probably like to see him gone as they see him as being too irresponsible and immature to run the company; his best bro friendship with author, Brian '),
(35, 'Movie 43', 'A series of interconnected short films follows a washed-up producer as he pitches insane story lines featuring some of the biggest stars in Hollywood.', 'Comedy', '4.4', '01:34:00', 'images/backgroundimg/movie43_halleberry.jpg', 'images/backgroundimg/1356510378092_movie-43-movie-poster.jpg', '2013', '6VneW1vtcWY', '2014-01-08 15:25:30', 'Ineffectual, ''has-been'' film-maker (Dennis Quaid) swindles his way into an interview with a film executive (Greg Kinnear) in order to pitch an outrageous and controversial comedy manuscript. After pitching the first of his thirteen offbeat fables, the dejected artist forces the rest of his disjointed allegory on the executive at gunpoint. He tells stories of a woman on a blind date with a man who has testicles growing from his neck, in another a smitten woman offers her neck to her boyfriend to '),
(36, 'The Polar Express', 'On Christmas Eve, a doubting boy boards a magical train that''s headed to the North Pole and Santa Claus'' home.', 'Family', '6.6', '01:40:00', 'images/backgroundimg/polar2.jpg', 'images/backgroundimg/polar.jpg', '2004', 'F8_GUrqe5tc', '2014-01-09 20:09:44', 'This is the story of a young hero boy on Christmas Eve who boards on a powerful magical train that''s headed to the North Pole and Santa Claus''s home. What unfolds is an an adventure which follows a doubting boy, who takes an extraordinary train ride to the North Pole; during this ride, he embarks on a journey of self-discovery which shows him that the wonder of life never fades for those who believe.'),
(38, 'The Dark Knight', 'When Batman, Gordon and Harvey Dent launch an assault on the mob, they let the clown out of the box, the Joker, bent on turning Gotham on itself and bringing any heroes down to his level.', 'action', '9.0', '02:32:00', 'images/backgroundimg/dark-knight-widescreen-batman-1057458_1680_1050.jpg', 'images/backgroundimg/the_dark_knight_poster.jpg', '2008', '5y2szViJlaY', '2014-01-08 15:34:34', 'Batman raises the stakes in his war on crime. With the help of Lieutenant Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the city streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as The Joker.'),
(37, 'Fight Club', 'An insomniac office worker looking for a way to change his life crosses paths with a devil-may-care soap maker and they form an underground fight club that evolves into something much, much more...', 'Drama', '8.9', '02:19:00', 'images/backgroundimg/Fight-Club.jpg', 'images/backgroundimg/fight-club-poster.jpg', '1999', 'SUXWAEX2jlg', '2014-01-08 15:24:42', 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground &quot;fight clubs&quot; forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.'),
(40, 'Winnie the Pooh', 'Eeyore has lost his tail, and Winnie the Pooh and his friends hold a contest to get him a new one.', 'Family', '7.3', '01:03:00', 'http://movieripped.com/wp-content/uploads/2013/03/tumblr_lqex4s1NWL1qbo4p0o1_1280.jpg', 'http://www.impawards.com/2011/posters/winnie_the_pooh_xlg.jpg', '2011', 'QbFz--GCkOM', '2014-01-08 15:48:15', 'During an ordinary day in Hundred Acre Wood, Winnie the Pooh sets out to find some honey. Misinterpreting a note from Christopher Robin, Owl convinces Tigger, Rabbit, Piglet, Pooh, Kanga, Roo, and Eeyore that their young friend has been captured by a creature named &quot;Backsoon&quot;, and they set out to save him.'),
(41, 'Toy Story', 'A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy''s room.', 'Family', '8.3', '01:21:00', 'images/backgroundimg/Toy_Story_Wallpaper.jpg', 'images/backgroundimg/toy_story_ver1_xlg.jpg', '1995', 'KYz2wyBy3kc', '2014-01-08 16:18:35', 'A little boy named Andy loves to be in his room, playing with his toys, especially his doll named &quot;Woody&quot;. But, what do the toys do when Andy is not with them, they come to life. Woody believes that he has life (as a toy) good. However, he must worry about Andy''s family moving, and what Woody does not know is about Andy''s birthday party. Woody does not realize that Andy''s mother gave him an action figure known as Buzz Lightyear, who does not believe that he is a toy, and quickly become'),
(43, 'Gamer', 'In a future mind-controlling game, death row convicts are forced to battle in a ''doom''-type environment. Convict Kable, controlled by Simon, a skilled teenage gamer, must survive 30 sessions in order to be set free. Or won''t he?', 'Sci-fi', '5.8', '01:35:00', 'http://www.visualhollywood.com/movies_2009/gamer/posters/wallpaper_001.jpg', 'http://e.movie.as/p/10242.jpg', '2009', 'P2g94xQmtHw', '2014-01-09 21:29:14', 'Set in a future-world where humans can control other humans in mass-scale, multi-player online gaming environments, a star player from a game called &quot;Slayers&quot; looks to regain his independence while taking down the game''s mastermind.'),
(44, 'Transformers', 'An ancient struggle between two Cybertronian races, the heroic Autobots and the evil Decepticons, comes to Earth, with a clue to the ultimate power held by a teenager.', 'Sci-fi', '7.2', '02:22:00', 'http://www.presidiacreative.com/wp-content/uploads/2009/07/113.jpg', 'http://dannebrandt.files.wordpress.com/2012/06/transformers-poster.jpg', '2007', 'dnD_Ar0P9dg', '2014-01-09 21:32:34', 'A long time ago, far away on the planet of Cybertron, a war is being waged between the noble Autobots (led by the wise Optimus Prime) and the devious Decepticons (commanded by the dreaded Megatron) for control over the Allspark, a mystical talisman that would grant unlimited power to whoever possesses it. The Autobots managed to smuggle the Allspark off the planet, but Megatron blasts off in search of it. He eventually tracks it to the planet of Earth (circa 1850), but his reckless desire for po'),
(45, 'Super Size Me', 'While examining the influence of the fast food industry, Morgan Spurlock personally explores the consequences on his health of a diet of solely McDonald''s food for one month.', 'Documentary', '7.4', '01:40:00', 'http://www.sunwarrior.com/news/wp-content/uploads/2012/11/McDonalds-alexallied-sxc.jpg', 'http://static1.solarmovie.so/images/movies/0390521_big.jpg', '2004', 'I1Lkyb6SU5U', '2014-01-09 21:39:09', 'Several legal suits have been brought against McDonald''s Restaurants that they are knowingly selling food that is unhealthy. Some of the court decisions have stated that the plaintiffs would have a claim if they could prove that eating the food every day for every meal is dangerous. As such, documentarian Morgan Spurlock conducts an unscientific experiment using himself as the guinea pig: eat only McDonald''s for thirty days, three meals a day. If he is asked by the clerk if he would like the mea'),
(46, 'The Hangover', 'Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing. They make their way around the city in order to find their friend before his wedding.', 'Comedy', '7.8', '01:40:00', 'http://www.entertainmentfuse.com/images/the-hangover-part-3.jpg', 'http://www.impawards.com/2009/posters/hangover_xlg.jpg', '2009', 'MzhlV6Dzvus', '2014-01-09 21:45:48', 'Angelenos Doug Billings and Tracy Garner are about to get married. Two days before the wedding, the four men in the wedding party - Doug, Doug''s two best buddies Phil Wenneck and Stu Price, and Tracy''s brother Alan Garner - hop into Tracy''s father''s beloved Mercedes convertible for a 24-hour stag party to Las Vegas. Phil, a married high school teacher, has the same maturity level as his students when he''s with his pals. Stu, a dentist, is worried about everything, especially what his controlling'),
(47, 'The Hobbit The Desolation of Smaug', 'The dwarves, along with Bilbo Baggins and Gandalf the Grey, continue their quest to reclaim Erebor, their homeland, from Smaug. Bilbo Baggins is in possession of a mysterious and magical ring.', 'Adventure', '8.4', '2:41', 'http://www.freefever.com/stock/the-hobbit-the-desolation-of-smaug.jpg', 'http://ia.media-imdb.com/images/M/MV5BMzU0NDY0NDEzNV5BMl5BanBnXkFtZTgwOTIxNDU1MDE@._V1_SX640_SY720_.jpg', '2013', 'http://www.youtube.com/watch?v=fnaojlfdUbs', '2014-01-17 01:43:34', 'The dwarves, along with Bilbo Baggins and Gandalf the Grey, continue their quest to reclaim Erebor, their homeland, from Smaug. Bilbo Baggins is in possession of a mysterious and magical ring.');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `firstname` varchar(10) NOT NULL,
  `lastname` varchar(20) NOT NULL,
  `username` varchar(16) DEFAULT NULL,
  `password` char(50) DEFAULT NULL,
  `email` varchar(20) NOT NULL,
  `is_active` int(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=22 ;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `firstname`, `lastname`, `username`, `password`, `email`, `is_active`) VALUES
(19, 'John', 'Ghavamzadeh', 'johnghav', 'b5e42f49ab3acf8f6c2ccf99f604a17f', 'john43top@msn.com', 1),
(20, 'arnold', 'schwarzenegger', 'guest', 'fd9ab41e47a9ef4f6477a8a000bf404f', 'john43top@gmail.com', 1),
(21, 'John', 'Ghavamzadeh', 'johnzade', 'b5e42f49ab3acf8f6c2ccf99f604a17f', 'john43top@msn.com', 1);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
